//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charles.Synap.Activities {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Charles.Synap.Activities.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Synap Document Analyzer 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ActivityTemplate_Description {
            get {
                return ResourceManager.GetString("ActivityTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synap Document Analyzer Api Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_APIKEY {
            get {
                return ResourceManager.GetString("Synap_APIKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synap Document Analyzer Api Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_APIKEY_Tip {
            get {
                return ResourceManager.GetString("Synap_APIKEY_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synap DA Convert Table To Excel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_DA_Convert_Excel {
            get {
                return ResourceManager.GetString("Synap_DA_Convert_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synap DA Request과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_DA_Request {
            get {
                return ResourceManager.GetString("Synap_DA_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synap DA Result과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_DA_Result {
            get {
                return ResourceManager.GetString("Synap_DA_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synap Document Analyer Endpoint 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_Endpoint {
            get {
                return ResourceManager.GetString("Synap_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Endpoint normally starts with http(s)://과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_Endpoint_Tip {
            get {
                return ResourceManager.GetString("Synap_Endpoint_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_ErrorMessage {
            get {
                return ResourceManager.GetString("Synap_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message when error occured during execution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_ErrorMessage_Tip {
            get {
                return ResourceManager.GetString("Synap_ErrorMessage_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel File Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_ExcelFIle {
            get {
                return ResourceManager.GetString("Synap_ExcelFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted Excel file path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_ExcelFIle_Tip {
            get {
                return ResourceManager.GetString("Synap_ExcelFIle_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unique request ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_FID {
            get {
                return ResourceManager.GetString("Synap_FID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used to retrieve result 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_FID_Tip {
            get {
                return ResourceManager.GetString("Synap_FID_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input File Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_InputFIlePath {
            get {
                return ResourceManager.GetString("Synap_InputFIlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input FIle Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_InputFIlePath_Tip {
            get {
                return ResourceManager.GetString("Synap_InputFIlePath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Zip File Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_OutputZipFilePath {
            get {
                return ResourceManager.GetString("Synap_OutputZipFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output zip file contains md, xml and json output file per page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_OutputZipFilePath_Tip {
            get {
                return ResourceManager.GetString("Synap_OutputZipFilePath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synap DA Result zip file 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_ResultZipFIle {
            get {
                return ResourceManager.GetString("Synap_ResultZipFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synap DA Result zip file contains all results ( md, xml, json)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_ResultZipFile_Tip {
            get {
                return ResourceManager.GetString("Synap_ResultZipFile_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_TableCount {
            get {
                return ResourceManager.GetString("Synap_TableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted table count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Synap_TableCount_Tip {
            get {
                return ResourceManager.GetString("Synap_TableCount_Tip", resourceCulture);
            }
        }
    }
}
